package static

const (
	//static
	CONFIG_FILE_NAME string = "config"
	CONFIG_FILE_TYPE string = "json"
	LOG_FILE         string = "info.log"
	APP_PORT         string = "APP_PORT"
	APP_HOST         string = "APP_HOST"
	MONGO_HOST       string = "MONGO_HOST"
	MONGO_DATABASE   string = "MONGO_DATABASE"
	MONGO_PORT       string = "MONGO_PORT"
	//messages
	MsgResponseStartProcess       string = "Start process -->   "
	MsgResponseStartApplication   string = "Starting the application...."
	MsgResponseStartError         string = "ERROR LEYENDO ARCHIVO DE CONFIGURACION"
	MsgResponseConnectedMongoDB   string = "Connected to MongoDB!"
	MsgResponseStartingNow        string = "STARTING NOW..."
	MsgResponseListingAll         string = "LISTANDO TODOS..."
	MsgResponseGettingOne         string = "OBTENIENDO UN OBJETO..."
	MsgResponseDeletingOne        string = "OBJETO BORRADO CORRECTAMENTE"
	MsgResponseCreatingOne        string = "OBJETO INSERTADO CORRECTAMENTE"
	MsgResponseUpdatingOne        string = "OBJETO EDITADO CORRECTAMENTE"
	MsgResponseObjectExists       string = "OBJETO EXISTENTE"
	MsgResponseServerError        string = "ERROR DE SERVIDOR"
	MsgResponseServerErrorWrongID string = "ERROR DE SERVIDOR: ID CON FORMATO DE VALOR INCORRECTO"
	MsgResponseServerErrorNoID    string = "ERROR DE SERVIDOR: ID INEXISTENTE"
	MsgResponseServerErrorNoData  string = "ERROR DE SERVIDOR: SIN DATOS EXISTENTES"
	MsgResponseInvalidRequest     string = "PAYLOAD/REQUEST INVALIDO"
	MsgApiRestTitle               string = "Microservice API Restful Example (Golang, Go Kit and MongoDB)"
	MsgApiRestDescription         string = "Simple CRUD using a data from persons as example"
	MsgApiRestVersion1            string = "1.0"
	MsgTestEXPECTED               string = "EXPECTED"
	//message middleware
	MsgUnauthorizatedLengthCI       string = "CI INCORRECTO (LONGITUD ENTRE 6 Y 11 DIGITOS)"
	MsgUnauthorizatedDigitCI        string = "CI INCORRECTO (TODOS LOS CARACTERES DEBEN SER DIGITOS)"
	MsgUnauthorizatedAlphanumericID string = "ID INCORRECTO (TODOS LOS CARACTERES DEBEN SER LETRAS O DIGITOS)"
	//message KAFKA
	MsgSavingDataKafka        string = "SAVING TO APACHE KAFKA"
	MsgReceivingDataFromKafka string = "START RECEIVING DATA FROM APACHE KAFKA"
	//parameters KAFKA
	KeyKafkaBootstrapServer   string = "bootstrap.servers"
	KeyKafkaGroupID           string = "group.id"
	KeyKafkaAutoOffsetReset   string = "auto.offset.reset"
	KafkaBootstrapServerValue string = "localhost:9092"
	KafkaGroupIDValue         string = "group-id-1"
	KafkaAutoOffsetResetValue string = "earliest"
	KafkaTopicInUse           string = "persons-topic1"
	//URLs
	URLStartingNow string = "/"
	URLApi         string = "/api"
	URLIndex       string = "/index"
	URLListingAll  string = "/list_persons"
	URLGettingOne  string = "/get_person"
	URLDeletingOne string = "/delete_person"
	URLCreatingOne string = "/create_person"
	URLUpdatingOne string = "/update_person"
	URLLocalhost   string = "localhost"
	//types responses
	ERROR   string = "ERROR"
	SUCCESS string = "SUCCESS"
	TEST    string = "TEST"
	OPTIONS string = "OPTIONS"
	//Database
	CollectionPerson string = "person"
	Field__id        string = "_id"
	FieldUpdated     string = "updated"
	FieldLastname    string = "lastname"
	FieldCi          string = "ci"
	OrderDesc        string = "-"
	OrderAsc         string = ""
	MongoDB__set     string = "$set"
	//functions
	FuncCreatePerson string = "CreatePerson"
	FuncUpdatePerson string = "UpdatePerson"
	FuncListPersons  string = "ListPersons"
	FuncGetPerson    string = "GetPerson"
	FuncDeletePerson string = "DeletePerson"
	//keyvals
	KeyType               string = "type"
	KeyURL                string = "URL"
	KeyMessage            string = "message"
	KeyMethod             string = "method"
	KeyTook               string = "took"
	KeyResponseMessage    string = "Message"
	KeyResponseStatusCode string = "StatusCode"
	KeyResponseData       string = "Data"
	KeyTs                 string = "ts"
	KeyCaller             string = "caller"
	KeyId                 string = "id"
	//http methods
	HTTP_POST   string = "POST"
	HTTP_GET    string = "GET"
	HTTP_DELETE string = "DELETE"
	//schemas
	SchemaHttp string = "http"
	//misc
	ValueEmpty string = ""
)
